# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='temp',
            new_name='tempdata',
        ),
    ]
